from core.domain.value_objects import Asset

PUBLIC_ISSUER = "GACKTN5DAZGWXRWB2WLM6OPBDHAMT6SJNGLJZPQMEZBUR4JUGBX2UK7V"
CHEQUE_PUBLIC_KEY = "GCYTGJ4VFRWYULX746TAOF4V6RYCEWG3TJ42JMG3GMJF7BJ44VVX6OUT"

EURMTL_ASSET = Asset(code="EURMTL", issuer=PUBLIC_ISSUER)
