from core.domain.value_objects import Asset

PUBLIC_ISSUER = "GACKTN5DAZGWXRWB2WLM6OPBDHAMT6SJNGLJZPQMEZBUR4JUGBX2UK7V"
CHEQUE_PUBLIC_KEY = "GCYTGJ4VFRWYULX746TAOF4V6RYCEWG3TJ42JMG3GMJF7BJ44VVX6OUT"

EURMTL_ASSET = Asset(code="EURMTL", issuer=PUBLIC_ISSUER)

PUBLIC_MMWB = "GBSNN2SPYZB2A5RPDTO3BLX4TP5KNYI7UMUABUS3TYWWEWAAM2D7CMMW"
USDC_ISSUER = "GA5ZSEJYB37JRC5AVCIA5MOP4RHTM335X2KGX3IHOJAPP5RE34K4KZVN"
USDM_ISSUER = "GDHDC4GBNPMENZAOBB4NCQ25TGZPDRK6ZGWUGSI22TVFATOLRPSUUSDM"

XLM_ASSET = Asset("XLM")
MTL_ASSET = Asset("MTL", PUBLIC_ISSUER)
BTCMTL_ASSET = Asset("BTCMTL", PUBLIC_ISSUER)
SATSMTL_ASSET = Asset("SATSMTL", PUBLIC_ISSUER)
USDC_ASSET = Asset("USDC", USDC_ISSUER)
USDM_ASSET = Asset("USDM", USDM_ISSUER)
